// flow-typed signature: 84a8a71d9c5446ee2d06732c0cdb1857
// flow-typed version: <<STUB>>/eslint-config-react-tools_v1.x.x/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-react-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-react-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-config-react-tools/index' {
  declare module.exports: $Exports<'eslint-config-react-tools'>;
}
declare module 'eslint-config-react-tools/index.js' {
  declare module.exports: $Exports<'eslint-config-react-tools'>;
}
