// flow-typed signature: be3ba45b1bbd06c7a94364125f548800
// flow-typed version: <<STUB>>/fetch-headers_v^2.0.0/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-headers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-headers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-headers/headers-es5.min' {
  declare module.exports: any;
}

declare module 'fetch-headers/headers' {
  declare module.exports: any;
}

declare module 'fetch-headers/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-headers/headers-es5.min.js' {
  declare module.exports: $Exports<'fetch-headers/headers-es5.min'>;
}
declare module 'fetch-headers/headers.js' {
  declare module.exports: $Exports<'fetch-headers/headers'>;
}
declare module 'fetch-headers/test/test.js' {
  declare module.exports: $Exports<'fetch-headers/test/test'>;
}
